/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as StudentSignupRouteImport } from './routes/student-signup'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as StudentRouteImport } from './routes/student'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as StudentSubjectsRouteImport } from './routes/student.subjects'
import { Route as StudentQuizzesRouteImport } from './routes/student.quizzes'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPlanRouteImport } from './routes/student.plan'
import { Route as StudentPaymentRouteImport } from './routes/student.payment'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentLibraryRouteImport } from './routes/student.library'
import { Route as StudentGradesRouteImport } from './routes/student.grades'
import { Route as StudentBookRouteImport } from './routes/student.book'
import { Route as StaffVerificationsRouteImport } from './routes/staff.verifications'
import { Route as StaffStudentsRouteImport } from './routes/staff.students'
import { Route as StaffResourcesRouteImport } from './routes/staff.resources'
import { Route as StaffMessagesRouteImport } from './routes/staff.messages'
import { Route as StaffBookingsRouteImport } from './routes/staff.bookings'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSignupRoute = StudentSignupRouteImport.update({
  id: '/student-signup',
  path: '/student-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSubjectsRoute = StudentSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizzesRoute = StudentQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPlanRoute = StudentPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPaymentRoute = StudentPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLibraryRoute = StudentLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBookRoute = StudentBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => StudentRoute,
} as any)
const StaffVerificationsRoute = StaffVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStudentsRoute = StaffStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => StaffRoute,
} as any)
const StaffResourcesRoute = StaffResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMessagesRoute = StaffMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBookingsRoute = StaffBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff-login': typeof StaffLoginRoute
  '/student': typeof StudentRouteWithChildren
  '/student-login': typeof StudentLoginRoute
  '/student-signup': typeof StudentSignupRoute
  '/subscription': typeof SubscriptionRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/messages': typeof StaffMessagesRoute
  '/staff/resources': typeof StaffResourcesRoute
  '/staff/students': typeof StaffStudentsRoute
  '/staff/verifications': typeof StaffVerificationsRoute
  '/student/book': typeof StudentBookRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/payment': typeof StudentPaymentRoute
  '/student/plan': typeof StudentPlanRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/subjects': typeof StudentSubjectsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/staff-login': typeof StaffLoginRoute
  '/student-login': typeof StudentLoginRoute
  '/student-signup': typeof StudentSignupRoute
  '/subscription': typeof SubscriptionRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/messages': typeof StaffMessagesRoute
  '/staff/resources': typeof StaffResourcesRoute
  '/staff/students': typeof StaffStudentsRoute
  '/staff/verifications': typeof StaffVerificationsRoute
  '/student/book': typeof StudentBookRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/payment': typeof StudentPaymentRoute
  '/student/plan': typeof StudentPlanRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/subjects': typeof StudentSubjectsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/staff': typeof StaffIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff-login': typeof StaffLoginRoute
  '/student': typeof StudentRouteWithChildren
  '/student-login': typeof StudentLoginRoute
  '/student-signup': typeof StudentSignupRoute
  '/subscription': typeof SubscriptionRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/messages': typeof StaffMessagesRoute
  '/staff/resources': typeof StaffResourcesRoute
  '/staff/students': typeof StaffStudentsRoute
  '/staff/verifications': typeof StaffVerificationsRoute
  '/student/book': typeof StudentBookRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/payment': typeof StudentPaymentRoute
  '/student/plan': typeof StudentPlanRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/subjects': typeof StudentSubjectsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/staff'
    | '/staff-login'
    | '/student'
    | '/student-login'
    | '/student-signup'
    | '/subscription'
    | '/staff/bookings'
    | '/staff/messages'
    | '/staff/resources'
    | '/staff/students'
    | '/staff/verifications'
    | '/student/book'
    | '/student/grades'
    | '/student/library'
    | '/student/messages'
    | '/student/payment'
    | '/student/plan'
    | '/student/profile'
    | '/student/quizzes'
    | '/student/subjects'
    | '/student/timetable'
    | '/staff/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/staff-login'
    | '/student-login'
    | '/student-signup'
    | '/subscription'
    | '/staff/bookings'
    | '/staff/messages'
    | '/staff/resources'
    | '/staff/students'
    | '/staff/verifications'
    | '/student/book'
    | '/student/grades'
    | '/student/library'
    | '/student/messages'
    | '/student/payment'
    | '/student/plan'
    | '/student/profile'
    | '/student/quizzes'
    | '/student/subjects'
    | '/student/timetable'
    | '/staff'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/staff'
    | '/staff-login'
    | '/student'
    | '/student-login'
    | '/student-signup'
    | '/subscription'
    | '/staff/bookings'
    | '/staff/messages'
    | '/staff/resources'
    | '/staff/students'
    | '/staff/verifications'
    | '/student/book'
    | '/student/grades'
    | '/student/library'
    | '/student/messages'
    | '/student/payment'
    | '/student/plan'
    | '/student/profile'
    | '/student/quizzes'
    | '/student/subjects'
    | '/student/timetable'
    | '/staff/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StaffRoute: typeof StaffRouteWithChildren
  StaffLoginRoute: typeof StaffLoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  StudentLoginRoute: typeof StudentLoginRoute
  StudentSignupRoute: typeof StudentSignupRoute
  SubscriptionRoute: typeof SubscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-signup': {
      id: '/student-signup'
      path: '/student-signup'
      fullPath: '/student-signup'
      preLoaderRoute: typeof StudentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-login': {
      id: '/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/subjects': {
      id: '/student/subjects'
      path: '/subjects'
      fullPath: '/student/subjects'
      preLoaderRoute: typeof StudentSubjectsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quizzes': {
      id: '/student/quizzes'
      path: '/quizzes'
      fullPath: '/student/quizzes'
      preLoaderRoute: typeof StudentQuizzesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/plan': {
      id: '/student/plan'
      path: '/plan'
      fullPath: '/student/plan'
      preLoaderRoute: typeof StudentPlanRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/payment': {
      id: '/student/payment'
      path: '/payment'
      fullPath: '/student/payment'
      preLoaderRoute: typeof StudentPaymentRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/library': {
      id: '/student/library'
      path: '/library'
      fullPath: '/student/library'
      preLoaderRoute: typeof StudentLibraryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/book': {
      id: '/student/book'
      path: '/book'
      fullPath: '/student/book'
      preLoaderRoute: typeof StudentBookRouteImport
      parentRoute: typeof StudentRoute
    }
    '/staff/verifications': {
      id: '/staff/verifications'
      path: '/verifications'
      fullPath: '/staff/verifications'
      preLoaderRoute: typeof StaffVerificationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/students': {
      id: '/staff/students'
      path: '/students'
      fullPath: '/staff/students'
      preLoaderRoute: typeof StaffStudentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/resources': {
      id: '/staff/resources'
      path: '/resources'
      fullPath: '/staff/resources'
      preLoaderRoute: typeof StaffResourcesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/messages': {
      id: '/staff/messages'
      path: '/messages'
      fullPath: '/staff/messages'
      preLoaderRoute: typeof StaffMessagesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/bookings': {
      id: '/staff/bookings'
      path: '/bookings'
      fullPath: '/staff/bookings'
      preLoaderRoute: typeof StaffBookingsRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface StaffRouteChildren {
  StaffBookingsRoute: typeof StaffBookingsRoute
  StaffMessagesRoute: typeof StaffMessagesRoute
  StaffResourcesRoute: typeof StaffResourcesRoute
  StaffStudentsRoute: typeof StaffStudentsRoute
  StaffVerificationsRoute: typeof StaffVerificationsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffBookingsRoute: StaffBookingsRoute,
  StaffMessagesRoute: StaffMessagesRoute,
  StaffResourcesRoute: StaffResourcesRoute,
  StaffStudentsRoute: StaffStudentsRoute,
  StaffVerificationsRoute: StaffVerificationsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface StudentRouteChildren {
  StudentBookRoute: typeof StudentBookRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentLibraryRoute: typeof StudentLibraryRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentPaymentRoute: typeof StudentPaymentRoute
  StudentPlanRoute: typeof StudentPlanRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentQuizzesRoute: typeof StudentQuizzesRoute
  StudentSubjectsRoute: typeof StudentSubjectsRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentBookRoute: StudentBookRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentLibraryRoute: StudentLibraryRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentPaymentRoute: StudentPaymentRoute,
  StudentPlanRoute: StudentPlanRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentQuizzesRoute: StudentQuizzesRoute,
  StudentSubjectsRoute: StudentSubjectsRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StaffRoute: StaffRouteWithChildren,
  StaffLoginRoute: StaffLoginRoute,
  StudentRoute: StudentRouteWithChildren,
  StudentLoginRoute: StudentLoginRoute,
  StudentSignupRoute: StudentSignupRoute,
  SubscriptionRoute: SubscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
